# Generated by Django 5.1.2 on 2024-10-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('T', 'TELMA'), ('O', 'ORANGE'), ('A', 'AIRTEL')], max_length=1),
        ),
    ]
