# Generated by Django 5.1.2 on 2024-10-31 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0003_delete_category_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zip_code',
        ),
    ]
