# Generated by Django 5.1.2 on 2024-10-31 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0004_alter_customer_options_remove_customer_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='customer',
            new_name='categories',
        ),
    ]
