# Generated by Django 5.1.2 on 2024-10-31 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0005_rename_customer_invoice_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_type',
            new_name='type_transactions',
        ),
    ]
