# Generated by Django 5.1.2 on 2024-10-31 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0006_rename_invoice_type_invoice_type_transactions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'detail_tarif'},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='categories',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='type_transactions',
            new_name='invoice_type',
        ),
    ]
