# Generated by Django 5.1.2 on 2024-10-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0007_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('D', 'Depot'), ('R', 'Retrait'), ('T', 'transefer')], max_length=1),
        ),
    ]
