# Generated by Django 5.1.2 on 2024-10-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0008_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Invoice', 'verbose_name_plural': 'Tarif_transaction'},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='customer',
            new_name='categories',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('D', 'Dépôt'), ('R', 'Retrait'), ('T', 'Transfert')], max_length=1),
        ),
    ]
