# Generated by Django 5.1.2 on 2024-10-31 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0009_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='categories',
            new_name='customer',
        ),
    ]
