# Generated by Django 5.1.2 on 2024-10-31 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0011_article_bonus_operateur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='total',
            new_name='montant',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='reference',
        ),
        migrations.RemoveField(
            model_name='article',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='article',
            name='unit_price',
        ),
    ]
