# Generated by Django 5.1.2 on 2024-10-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0012_rename_total_article_montant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bonus_operateur',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='bonus_personalise_montant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='frais',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
