# Generated by Django 5.1.2 on 2024-11-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0013_alter_article_bonus_operateur_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='bonus_personalise_montant',
        ),
        migrations.RemoveField(
            model_name='article',
            name='reference',
        ),
        migrations.AddField(
            model_name='article',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='bonus_personalise',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='bonus_operateur',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='frais',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='montant',
            field=models.CharField(max_length=32),
        ),
    ]
