# Generated by Django 5.1.2 on 2024-11-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0014_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
    ]
