# Generated by Django 5.1.2 on 2024-11-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0015_invoice_bonus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Tarif_pour_les_transaction'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Invoice', 'verbose_name_plural': 'Type_de_tarif'},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='bonus',
        ),
    ]
