# Generated by Django 5.1.2 on 2024-10-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Type_transactions',
            },
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=265),
        ),
    ]
