# Generated by Django 5.1.2 on 2024-10-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_description_alter_expense_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='description',
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(),
        ),
    ]
