# Generated by Django 5.1.2 on 2024-10-31 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_delete_description_alter_expense_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'type_transaction'},
        ),
    ]
