# Generated by Django 5.1.2 on 2024-10-31 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
