# Generated by Django 5.1.2 on 2024-10-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(choices=[('D', 'Dépôt'), ('R', 'Retrait'), ('T', 'Transfert')], max_length=1),
        ),
    ]
