# Generated by Django 5.1.2 on 2024-10-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_expense_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bonus',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='expense',
            name='reference',
            field=models.CharField(default='N/A', max_length=32),
        ),
    ]
