# Generated by Django 5.1.2 on 2024-11-01 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_expense_options_delete_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name_plural': 'transactions'},
        ),
    ]
