# Generated by Django 5.1.2 on 2024-11-07 03:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashpoint_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('operateur', models.CharField(choices=[('TELMA', 'Telma'), ('ORANGE', 'Orange'), ('AIRTEL', 'Airtel')], max_length=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_management.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Solde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('TELMA', 'Telma'), ('ORANGE', 'Orange'), ('AIRTEL', 'Airtel')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cashpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_management.employeur')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_management.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('TELMA', 'Telma'), ('ORANGE', 'Orange'), ('AIRTEL', 'Airtel')], max_length=10)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bonus_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_management.employeur')),
            ],
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('TELMA', 'Telma'), ('ORANGE', 'Orange'), ('AIRTEL', 'Airtel')], max_length=10)),
                ('montant', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('employeur_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_cible', to='stock_management.employeur')),
                ('employeur_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_source', to='stock_management.employeur')),
            ],
        ),
    ]
